# Generated by Django 2.2.6 on 2020-03-30 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha_basica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('dni', models.DecimalField(decimal_places=0, max_digits=8)),
                ('edad', models.DecimalField(decimal_places=0, max_digits=8)),
            ],
        ),
    ]
